spring:
  profiles:
    include: default, dev
  flyway:
    enabled: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: 'refresh' # or '*' for all
  endpoint:
    health:
      enabled: true

henry:
  location: "hleong25/zillow-hackweek/hw20henry.xml rev 2"

gitProperty1: "from hleong25/zillow-hackweek - git property 1"
gitProperty2: "from hleong25/zillow-hackweek - git property 2"

